apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dave-binding
  namespace: rajesh-app
subjects:
- kind: User
  name: dave
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: read-write-role
  apiGroup: rbac.authorization.k8s.io
